[package]
name = "notOS"
authors = ["notforest"]
version = "0.1.1"
readme = "README.md"
edition = "2021"

[[test]]
name = "int_tests"

[dependencies]
proc_macros = { path = "./proc_macros" }

[profile.release]
codegen-units = 1
lto = true

[features]
default = []
virt_qemu = []
