[package]
name = "notOS-primitive-data-types"
version = "0.1.0"
edition = "2024"

[dependencies]
no-std-compat = { version = "0.4.1", features = [ "alloc" ] }
build_const   = { version = "0.2.2", default-features = false }

[build-dependencies]
buildConfig = { package = "notOS-build-config", path = "../../buildConfig"}

[features]
std = [ "no-std-compat/std" ]
