[package]
name = "notOS-memory"
version = "0.1.0"
edition = "2024"

[dependencies]
osPrimitives = { package = "notOS-primitive-data-types", path = "../dataStructures/primitives/" }
osStructures = { package = "notOS-data-structures", path = "../dataStructures/structures/" }

no-std-compat = { version = "0.4.1", features = [ "alloc" ] }

[features]
std = [ "no-std-compat/std" ]
