[package]
name = "notOS-task-virtualization"
version = "0.1.0"
edition = "2024"

[dependencies]
osPrimitives = { package = "notOS-primitive-data-types", path = "../dataStructures/primitives" }

bitfields = { version = "2.0.6" }
no-std-compat = { version = "0.4.1", features = [ "alloc" ] }

[features]
std = [ "no-std-compat/std" ]
